## Where the samples will be written
save_data: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/run/example
## Where the vocab(s) will be written
src_vocab: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/run/example.vocab.src
tgt_vocab: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/en2es/preprocess/train.bpe.en
        path_tgt: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/en2es/preprocess/train.bpe.es
    valid:
        path_src: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/en2es/preprocess/valid.bpe.en
        path_tgt: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/en2es/preprocess/valid.bpe.es

# Vocabulary files that were just created
src_vocab: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/run/example.vocab.src
tgt_vocab: /content/TranslateAlignRetrieve/src/tar/src/nmt/data/run/example.vocab.tgt

both_embeddings: /content/gdrive/MyDrive/glove/glove.6B.300d.txt

# supported types: GloVe, word2vec
embeddings_type: "GloVe"

# word_vec_size need to match with the pretrained embeddings dimensions
word_vec_size: 300

save_model: /content/gdrive/MyDrive/data/exp/model.en-es
save_checkpoint_steps: 3000
keep_checkpoint: 3
seed: 3435
train_steps: 100000
valid_steps: 10000
warmup_steps: 8000
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

# this param is used to start from a check_point
train_from: /content/gdrive/MyDrive/data/model.en-es_step_60000.pt

world_size: 1
gpu_ranks:
- 0
